export const inventoryTableData = [
    {
        kode: "229",
        namaBarang: "White",
        type: "Pro",
        stokOrder: "50 Kg",
        stokKeluar: "40 Kg",
        mutasiMasuk: "0 Kg",
        mutasiKeluar: "0 Kg",
        totalStok: "17 Kg",
        harga: "Rp. 16.000",
        tanggal: "12 Januari 2025",
    },
    {
        kode: "329",
        namaBarang: "Yellow",
        type: "Super",
        stokOrder: "35 Kg",
        stokKeluar: "15 Kg",
        mutasiMasuk: "0 Kg",
        mutasiKeluar: "0 Kg",
        totalStok: "31 Kg",
        harga: "Rp. 20.000",
        tanggal: "12 Januari 2025",
    },
    {
        kode: "331",
        namaBarang: "Green",
        type: "Super",
        stokOrder: "30 Kg",
        stokKeluar: "20 Kg",
        mutasiMasuk: "0 Kg",
        mutasiKeluar: "0 Kg",
        totalStok: "19 Kg",
        harga: "Rp. 20.000",
        tanggal: "12 Januari 2025",
    },
    {
        kode: "515",
        namaBarang: "Black",
        type: "Gloss",
        stokOrder: "45 Kg",
        stokKeluar: "35 Kg",
        mutasiMasuk: "0 Kg",
        mutasiKeluar: "0 Kg",
        totalStok: "15 Kg",
        harga: "Rp. 35.000",
        tanggal: "12 Januari 2025",
    },
    {
        kode: "525",
        namaBarang: "White",
        type: "Gloss",
        stokOrder: "53 Kg",
        stokKeluar: "43 Kg",
        mutasiMasuk: "0 Kg",
        mutasiKeluar: "0 Kg",
        totalStok: "25 Kg",
        harga: "Rp. 35.000",
        tanggal: "12 Januari 2025",
    },
    {
        kode: "201",
        namaBarang: "Gray",
        type: "Pro",
        stokOrder: "19 Kg",
        stokKeluar: "10 Kg",
        mutasiMasuk: "0 Kg",
        mutasiKeluar: "0 Kg",
        totalStok: "25 Kg",
        harga: "Rp. 35.000",
        tanggal: "12 Januari 2025",
    },
];
